#include "/Engine/Public/Platform.ush"

RWTexture2D<float3> RenderTarget;
float testValue;


[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void DeformationCS(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint GroupIndex : SV_GroupIndex )
{
	// Simple checkerboard
	int x = floor(DispatchThreadId.x / 16.f);
	int y = floor(DispatchThreadId.y / 16.f);
	int c = (x + y % 2) % 2;
	
	RenderTarget[DispatchThreadId.xy] = float3(c, testValue, c);
}